### ISSUE TITLE
holland-commvault plugin is broken in 1.1.5

### ISSUE THREAD

**Issue by prwhitaker** [holland-backup/holland#208]
There are two issues seen with the holland commvault plugin in version 1.1.5

1. The script that CommVault calls has moved from `/usr/sbin/holland_cvmysqlsv` to `/usr/bin/holland_cvmysqlsv`, which CommVault is not expecting to happen, so it can't find the command to run

1. When the new script is run, it throws an error from python
An example with typical parameters passed by CommVault:
```
# /usr/bin/holland_cvmysqlsv -bkplevel 1 -attempt 1 -job 123456 -cn 999999-111111 -vm Instance001
Holland (commvault agent) 1.1.5 started with pid 21101
Traceback (most recent call last):
  File "/usr/bin/holland_cvmysqlsv", line 9, in <module>
    load_entry_point('holland-commvault==1.1.5', 'console_scripts', 'holland_cvmysqlsv')()
  File "/usr/lib/python2.7/site-packages/holland_commvault/commvault.py", line 93, in main
    if run(['backup'] + args.bksets):
  File "/usr/lib/python2.7/site-packages/holland/core/command/__init__.py", line 41, in run
    cmdobj = commands[opts.command]()
AttributeError: 'list' object has no attribute 'command'
```

This worked ok in version 1.0.14:
```
# /usr/sbin/holland_cvmysqlsv -bkplevel 1 -attempt 1 -job 123456 -cn 999999-111111 -vm Instance001
Holland (commvault agent) 1.0.14 started with pid 8497
--- Starting backup run ---
Creating backup path /var/spool/holland/default/20181003_115320
Estimating size of mysqldump backup
Estimated Backup Size: 2.46MB
Adjusting estimated size by 0.50 to 1.23MB
Starting backup[default/20181003_115320] via plugin mysqldump
Using mysqldump executable: /usr/bin/mysqldump
mysqldump version 5.7.22
Using mysqldump option --flush-privileges
Using mysqldump option --max-allowed-packet=128M
Using gzip compression level 1 with args 
Wrote backup manifest /var/spool/holland/default/20181003_115320/backup_data/MANIFEST.txt
Executing: /usr/bin/mysqldump --defaults-file=/var/spool/holland/default/20181003_115320/my.cnf --flush-privileges --max-allowed-packet=128M --lock-tables mysql
Executing: /usr/bin/mysqldump --defaults-file=/var/spool/holland/default/20181003_115320/my.cnf --flush-privileges --max-allowed-packet=128M --single-transaction sys
Final on-disk backup size 342.60KB
13.60% of estimated size 2.46MB
Backup completed in 0.56 seconds
No backups purged
Released lock /etc/holland/backupsets/default.conf
--- Ending backup run ---
```

**Comment by soulen3** [comment]
This issue was caused when holland was updated to using Argprase instead of Optparse.  This meant that holland_cvmysqlsv was passing the wrong object type to the run() function.  This has been fixed in 1.1.6
